# Site settings
title: ADA
tag_text: Is the book better than the movie ?
baseurl: "/ada-epfl"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
